### ISSUE TITLE
7 LTS compatibility

### ISSUE THREAD

**Issue by h3nn3s** [svewap/cleverreach#1]
Hi Sven,

thanks for your extension. This one is currently not 7 LTS compatible, as stated in the ext_emconf file, because the TypoScriptService Class got moved in 8 LTS and is not found in 7.

https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.7/Important-78650-TypoScriptServiceClassMovedFromExtbaseToCore.html

**Comment by svewap** [comment]
Thank you! It will be fixed in the next release.

**Comment by schliesser** [comment]
In the extensions composer.json and em_conf.php it's still marked to be compatible with 7.6.

0.1.6 isn't even anymore compatible with 8.7. See #30
