### ISSUE TITLE
Will there ever be a new release?

### ISSUE THREAD

**Issue by Nemo64** [svewap/cleverreach#10]
I did fix an identifier which makes this extension for my use case unusable (#9) but the change is still not released which means i have use a dev version which i kind of dislike.

**Comment by svewap** [comment]
The problem is the time. This is just a project of many other projects. And I don't get paid for this so I have to do this in my free time. A new release will come, but I don't know the time.

**Comment by Nemo64** [comment]
I totally understand that. Sorry if my title was a little provokative.
