### ISSUE TITLE
Fehler bei Abmeldung mit Powermail

### ISSUE THREAD

**Issue by ipnextOne** [svewap/cleverreach#11]
Hallo, 

ich bekomme bei der Abmeldung über Powermail immer die Nachricht: 
"E-Mail: Diese Email-Adresse befindet sich nicht in unserer Liste"
Da ich mich aber kurz vorher mit der E-Mail Adresse angemeldet habe und auch von CleaverReach eine Bestätigung bekommen habe, kann das nicht sein.
Muss ich irgend etwas beachten damit es funktioniert?

Vielen Dank 
Mathias

**Comment by svewap** [comment]
Für Support bitte andere Kanäle benutzen.
https://docs.typo3.org/typo3cms/extensions/cleverreach/Introduction/Support/Index.html
