### ISSUE TITLE
subscribers not added

### ISSUE THREAD

**Issue by tintusumith** [svewap/cleverreach#25]
Hi, 
I installed cleverreach extension in our typo3 and added cleverreach API settings. We used CleverReach Optin form(ext:forms) and included in typo3 page. For getting client id, group id, form id, i created cleverreach account and created  demo list, form and app. After this  I submitted form with valid email id. But nothing will happen and i didnt get any mail or no subscribers added in cleverreach demo list. How can do this..

**Comment by svewap** [comment]
I apologize, but this is not a support forum. Errors can have many different causes (server infrastructure, firewalls, ...) . If you have concrete evidence of a bug or want to make an improvement, you are welcome to open an issue here.

**Comment by tintusumith** [comment]
Hi ,
That was not an issue. In cleverreach documentation screenshot there is a place for giving client id. I gave client id which got from cleverreach(https://eu2.cleverreach.com/admin/account_rest.php) . But actually  client id is not required for cleverreach authentication. Instead of that it required customer id which got after account creation in cleverreach  . Please find the screen shots.Could you please change client-id to customer id in extension documentation. Otherwise there will be confusion for users.
![REST API   CleverReach](https://user-images.githubusercontent.com/35957640/59770222-44ae5880-92c5-11e9-9990-06918ab213ea.png)
![Installation — cleverreach 0 1 5 documentation](https://user-images.githubusercontent.com/35957640/59770224-44ae5880-92c5-11e9-8de9-e01cf23b7595.png)
