### ISSUE TITLE
How to transmit attributes to CleaverReach

### ISSUE THREAD

**Issue by stroebjo** [svewap/cleverreach#5]
I installed the extension and successfully added a new recipient to my CleverReach list. But how can I sent attributes (lastname, firstname, gender, i.e.) to CleverReach? In the code I found the `cleverreachField` Property: 

https://github.com/svewap/cleverreach/blob/de297bc6e3f3077e50b815ff872d6e7cc7b866a1/Classes/Form/Finishers/CleverreachFinisher.php#L56

But how do I set this property inside the Powermail form editor? I found nothing in that regard in the [editor docs](https://docs.typo3.org/typo3cms/extensions/cleverreach/UsersManual/Powermail/Index.html).

**Comment by Skinwalker** [comment]
This should work automatically if the field in the form and in the group are named the same.

**Comment by stroebjo** [comment]
Thanks, for pointing that out. Works now as Expected
